apiVersion: v1
kind: Pod
metadata:
  name: resource-demo
spec:
  containers:
  - name: demo-container
    image: nginx
    resources:
      requests:
        memory: "64Mi"   # Guaranteed 64 Megabytes
        cpu: "250m"      # Guaranteed 0.25 of a CPU core
      limits:
        memory: "128Mi"  # Hard cap; will OOMKill if exceeded
        cpu: "500m"      # Hard cap; will throttle if exceeded
