apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: my-container
    image: nginx
    env:
      - name: DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: db-user-pass  # The name of the secret
            key: username       # The key within the secret
